name: Pact

on:
  push:
    branches:
      - main

env:
  PACT_BROKER_BASE_URL:  ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN:  ${{ secrets.PACT_BROKER_TOKEN }}
jobs:
  pact:
    runs-on: ubuntu-latest
    name: Pact

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Install Go.
          curl -L -o go1.16.6.linux-amd64.tar.gz https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
          rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
          echo "$PATH:/usr/local/go/bin" >> $GITHUB_PATH

          # Install Pact.
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.65/pact-1.88.65-linux-x86_64.tar.gz
          rm -rf /usr/local/pact && sudo tar -C /usr/local -xzf pact-1.88.65-linux-x86_64.tar.gz
          echo "$PATH:/usr/local/pact/bin" >> $GITHUB_PATH

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Extract version
        shell: bash
        run: |
          echo "##[set-output name=hash;]$(echo $(git rev-parse --short "$GITHUB_SHA"))"
        id: extract_branch

      - name: Run Tests
        env:
          VERSION: ${{ steps.extract_branch.outputs.hash }}
        run: go test ./...
